---
name: Feature request
description: Suggest an idea or improvement for AddMan
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: What problem would this solve?
      description: Describe the use case or pain point.
      placeholder: I want AddMan to ...
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: How might it work? An example `addman.yaml` snippet helps.
      render: yaml
    validations:
      required: false
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
    validations:
      required: false
