---
name: Builder

env:
  MONITORED_FILES: "build.yaml config.yaml Dockerfile rootfs"

"on":
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  init:
    name: Initialize builds
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.filter.outputs.changed }}
      changed_addons: ${{ steps.filter.outputs.changed_addons }}
    steps:
      - name: Check out the repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

      - name: Get changed files
        id: changed_files
        uses: tj-actions/changed-files@c948ac82ccdd9566ea9476f8cccc058dc296afc4  # v47.0.2

      - name: Find add-on directories
        id: addons
        uses: home-assistant/actions/helpers/find-addons@868e6cb4607727d764341a158d98872cd63fa658  # master

      - name: Filter changed add-ons
        id: filter
        env:
          ADDONS: ${{ steps.addons.outputs.addons }}
          CHANGED_FILES: ${{ steps.changed_files.outputs.all_changed_files }}
        run: |
          changed_addons=()
          if [[ "${CHANGED_FILES}" =~ \.github/workflows/(builder|build-app)\.yaml ]]; then
            changed_addons=(${ADDONS})
          else
            for addon in ${ADDONS}; do
              for file in ${MONITORED_FILES}; do
                if [[ "${CHANGED_FILES}" =~ ${addon}/${file} ]]; then
                  changed_addons+=("${addon}")
                  break
                fi
              done
            done
          fi

          if [[ ${#changed_addons[@]} -gt 0 ]]; then
            echo "Changed add-ons: ${changed_addons[*]}"
            echo "changed=true" >> "$GITHUB_OUTPUT"
            echo "changed_addons=$(jq -nc '$ARGS.positional' --args "${changed_addons[@]}")" >> "$GITHUB_OUTPUT"
          else
            echo "No add-on had any monitored files changed (${{ env.MONITORED_FILES }})";
            echo "changed=false" >> "$GITHUB_OUTPUT"
          fi

  build-addon:
    needs: init
    if: needs.init.outputs.changed == 'true'
    name: Build ${{ matrix.addon }}
    permissions:
      contents: read
      id-token: write
      packages: write
    strategy:
      fail-fast: false
      matrix:
        addon: ${{ fromJSON(needs.init.outputs.changed_addons) }}
    uses: ./.github/workflows/build-app.yaml
    with:
      app: ${{ matrix.addon }}
      publish: ${{ github.event_name == 'push' }}
    secrets: inherit
